export const APPLY_RAZA_REQ = "APPLY_RAZA_REQ";
export const APPLY_RAZA_RESP = "APPLY_RAZA_RESP";

export const GET_RAZA_TYPE_REQ = "GET_RAZA_TYPE_REQ";
export const GET_RAZA_TYPE_RESP = "GET_RAZA_TYPE_RESP";

export const GET_ALL_RAZA_REQ = "GET_ALL_RAZA_REQ";
export const GET_ALL_RAZA_RESP = "GET_ALL_RAZA_RESP";

export const GET_MUMINEEN_BY_ID_REQ = "GET_MUMINEEN_BY_ID_REQ";
export const GET_MUMINEEN_BY_ID_RESP = "GET_MUMINEEN_BY_ID_RESP";

export const UPDATE_RAZA_REQ = "UPDATE_RAZA_REQ";
export const UPDATE_RAZA_RESP = "UPDATE_RAZA_RESP";

export const DELETE_RAZA_REQ = "DELETE_RAZA_REQ";
export const DELETE_RAZA_RESP = "DELETE_RAZA_RESP";

export const GET_USER_REQ = "GET_USER_REQ";
export const GET_USER_RESP = "GET_USER_RESP";